// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/common/cron/start": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/cron/stat": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/common/cron/stop": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/dev/certificateStatusIIH": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dev"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/dev/enrollRoamingCert": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dev"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/dev/generateResetPinCode": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dev"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/dev/requestRevoke/{requestCode}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dev"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Request Code",
                        "name": "requestCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/dev/resetPin/{resetCode}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dev"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Reset Code",
                        "name": "resetCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/roaming/certificateStatusIIH": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roaming"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/roaming/enrollRoamingCert": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roaming"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/roaming/generateResetPinCode": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roaming"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/roaming/requestRevoke": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roaming"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/roaming/resetPin": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Roaming"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/mycrs",
	Schemes:          []string{},
	Title:            "Swagger MYCRS API",
	Description:      "This is a mycrs server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
